import{a as w,S as H,i as u}from"./assets/vendor-eded45c0.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const M="https://pixabay.com/api/",O="43356072-8dcb25da9aa802a65c4e2a4ec";async function g(s,e){const a=new URLSearchParams({key:O,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15});return(await w(`${M}?${a}`)).data}function y(s){return s.map(({webformatURL:e,largeImageURL:a,tags:n,likes:t,views:o,comments:i,downloads:S})=>`<li class="gallery-item">
        <div class="thumb">
            <a class="gallery-link" href="${a}">
              <img
                class="gallery-image"
                src="${e}"
                alt="${n}"
              />
            </a>
              <ul class="description-list">
                <li class="description-items"><span class="accent">Likes </span>${t}</li>
                <li class="description-items"><span class="accent">Views </span>${o}</li>
                <li class="description-items"><span class="accent">Comments </span>${i}</li>
                <li class="description-items"><span class="accent">Downloads </span>${S}</li>
              </ul>
        </div>
      </li>`).join("")}const L=document.querySelector(".js-search-form "),h=document.querySelector(".search-input"),m=document.querySelector("ul.gallery"),q=document.querySelector(".loader"),d=document.querySelector(".load-more");function l(){q.classList.toggle("hidden")}function p(){d.classList.add("hidden")}function v(){d.classList.remove("hidden")}function $(s){const e=s.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}let f="";const b=new H(".gallery a",{captionsData:"alt",captionDelay:250});let r=1,c;L.addEventListener("submit",P);d.addEventListener("click",E);window.addEventListener("scroll",function(){const{scrollTop:s,scrollHeight:e,clientHeight:a}=document.documentElement;s+a>=e-5&&r>=c&&d.classList.contains("hidden")&&u.info({title:"",message:"We're sorry, but you've reached the end of search results!",position:"bottomRight",timeout:3e3,pauseOnHover:!1})});async function P(s){if(s.preventDefault(),m.innerHTML="",r=1,d.classList.contains("hidden")||p(),h.value.trim()==="")return u.error({title:"",message:"The field can not be empty!!!",position:"topCenter",timeout:3e3,pauseOnHover:!1});f=h.value,l();try{const e=await g(f,r);e.hits.length===0?u.error({title:"",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3,pauseOnHover:!1}):(m.insertAdjacentHTML("beforeend",y(e.hits)),b.refresh(),c=Math.ceil(e.totalHits/e.hits.length),r<c&&v())}catch(e){alert(e.message)}finally{L.reset()}l()}async function E(){r+=1,l();try{const s=await g(f,r);if(console.log("Loaded page:",r),console.log("Total pages:",c),m.insertAdjacentHTML("beforeend",y(s.hits)),b.refresh(),r>=c)console.log("Last page reached"),u.info({title:"",message:"We're sorry, but you've reached the end of search results!",position:"bottomRight",timeout:3e3,pauseOnHover:!1}),l(),p();else{const e=document.querySelector(".gallery-item");$(e),v()}}catch(s){alert(s.message),p()}finally{l()}}
//# sourceMappingURL=commonHelpers.js.map
